### PR TITLE
simple_lmk: ressign missing defines for kernel 3.10

### PR DESCRIPTION
**Pull request by lzlrd**
Signed-off-by: Laster K. (lazerl0rd) <officiallazerl0rd@gmail.com>

### CODE REVIEW

**Comment by mortezadadgar** [comment]
why he should care?

**Comment by lzlrd** [comment]
@mortezadadgar because I'm in his group and I told him directly beforehand that I'd PR this change - he just wanted it tested first.

This repo isn't aiming at SLMK for one kernel version - it's aiming it at a range.

**Comment by lzlrd** [comment]
Look at https://github.com/kerneltoast/simple_lmk/blob/master/simple_lmk.patch#L116 for example.

**Comment by mortezadadgar** [comment]
@lazerl0rd
Sorry if I was being rude

**Comment by lzlrd** [comment]
@mortezadadgar no worries, I'm sure you didn't mean it like that.

**Comment by kerneltoast** [comment]
Fixed: https://github.com/kerneltoast/simple_lmk/commit/34f4988a92bcf3100d2d164b73869f043e12bd03

**Comment by Jprimero15** [comment]
Can u add linux 3.4 Support

**Comment by artem** [comment]
> Can u add linux 3.4 Support

yes

**Comment by mortezadadgar** [comment]
> Can u add linux 3.4 Support

The current version doesn't even support 3.10 and you wants 3.4 support??

**Comment by lazerl0rd** [comment]
@mortezadadgar 3.10 was supported with this patch, wasn’t it? But yeah, 3.4 isn’t getting support unless you want to propose a change or fork this @Jprimero15. There’s the issue that 3.10 and below have LMK in staging, which is different to newer kernels and as such the patch can’t apply cleanly.

Anyways, this isn’t the place to request for 3.4 support. You should create a new issue.

**Comment by Jprimero15** [comment]
This could work.. But we need this atomic backport.. Which idk which commits exactly. . or just use WRITE_ONCE again instead of this atomic functions.. WRITE_ONCE also nit supported on thus ancient kernel version but it could be easily backported

**Comment by lzlrd** [comment]
3.4 isn’t getting support unless you want to propose a change or fork this (to remove the multi copy atomic helpers) @Jprimero15. There’s the issue that 3.10 and below have LMK in staging too, which is different to newer kernels and as such the patch can’t apply cleanly.

Anyways, this isn’t the place to request for 3.4 support. You should create a new issue.

**Pull request closed without merging**
